// swift-tools-version: 5.7
import PackageDescription

// GENERATED by scripts/publish-ios-spm.sh — do not hand-edit.
//
// Both products are SINGLE-MODULE xcframeworks. The previous multi-target build
// produced interfaces beginning `@_exported import BillDogCore`, which Swift
// resolves against the framework search path — not against sibling
// .swiftmodule dirs inside the framework — so the artifacts resolved,
// checksummed, and could not be imported.
//
// The full product is BillDogFull, not BillDog: BillDogPaywall declares
// `public class BillDog`, and a module of the same name makes Swift's
// self-qualified interface names resolve to the class (swiftlang/swift#56573).
// The CLASS is unchanged — `BillDog.shared.…` still works. Only the import moved:
//
//     - import BillDog
//     + import BillDogFull
//
let package = Package(
    name: "BillDog",
    platforms: [.iOS(.v15), .macOS(.v12)],
    products: [
        .library(name: "BillDogFull", targets: ["BillDogFull"]),
        .library(name: "BillDogEng",  targets: ["BillDogEng"])
    ],
    dependencies: [
        // BillDogFull's paywall renderer imports Lottie, so it appears in that
        // product's module interface and the consumer must resolve it too.
        .package(url: "https://github.com/airbnb/lottie-ios.git", from: "4.4.0")
    ],
    targets: [
        .binaryTarget(
            name: "BillDogFull",
            url: "https://github.com/billdogai/billdog-ios-spm/releases/download/v1.0.0-beta.2/BillDogFull.xcframework.zip",
            checksum: "2eac227e7be54a36b6467f9c8c83256881ab8e21d0aec1bbd123566bab243b9d"
        ),
        .binaryTarget(
            name: "BillDogEng",
            url: "https://github.com/billdogai/billdog-ios-spm/releases/download/v1.0.0-beta.2/BillDogEng.xcframework.zip",
            checksum: "77442c9153eb0cdbd096566d9beebffb9061cfd193ffde34c01eca24225429ec"
        )
    ]
)
