// swift-tools-version: 5.7
import PackageDescription

// GENERATED by scripts/publish-ios-spm.sh — do not hand-edit.
//
// Both products are SINGLE-MODULE xcframeworks. The previous multi-target build
// produced interfaces beginning `@_exported import BillDogCore`, which Swift
// resolves against the framework search path — not against sibling
// .swiftmodule dirs inside the framework — so the artifacts resolved,
// checksummed, and could not be imported.
//
// The full product is BillDogFull, not BillDog: BillDogPaywall declares
// `public class BillDog`, and a module of the same name makes Swift's
// self-qualified interface names resolve to the class (swiftlang/swift#56573).
// The CLASS is unchanged — `BillDog.shared.…` still works. Only the import moved:
//
//     - import BillDog
//     + import BillDogFull
//
let package = Package(
    name: "BillDog",
    platforms: [.iOS(.v15), .macOS(.v12)],
    products: [
        .library(name: "BillDogFull", targets: ["BillDogFull"]),
        .library(name: "BillDogEng",  targets: ["BillDogEng"])
    ],
    dependencies: [
        // BillDogFull's paywall renderer imports Lottie, so it appears in that
        // product's module interface and the consumer must resolve it too.
        .package(url: "https://github.com/airbnb/lottie-ios.git", from: "4.4.0")
    ],
    targets: [
        .binaryTarget(
            name: "BillDogFull",
            url: "https://github.com/billdogai/billdog-ios-spm/releases/download/v1.0.0-beta.2/BillDogFull.xcframework.zip",
            checksum: "cc2d2f0d2d8e69f73419c67e4e61b2fb3b3eb253677db6284225be36e4fcd1a0"
        ),
        .binaryTarget(
            name: "BillDogEng",
            url: "https://github.com/billdogai/billdog-ios-spm/releases/download/v1.0.0-beta.2/BillDogEng.xcframework.zip",
            checksum: "4852b1c62e63975c890b7bf2e9325a47878f1afa1671900875d8a015ffc0549d"
        )
    ]
)
